# https://typeof.net/Iosevka/customizer
[buildPlans.Bersevka]
family = "Bersevka"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.Bersevka.variants.design]
three = "flat-top-serifless"
five = "upright-arched-serifless"
seven = "straight-serifless-crossbar"
zero = "dotted"
capital-a = "straight-serifless"
capital-g = "toothless-corner-serifless-hooked"
capital-j = "serifless"
capital-q = "crossing"
capital-s = "serifless"
f = "flat-hook-serifless-crossbar-at-x-height"
j = "flat-hook-serifed"
t = "flat-hook-short-neck2"
punctuation-dot = "square"
paren = "normal"
at = "fourfold"
question = "corner"

[buildPlans.Bersevka.variants.oblique]
three = "flat-top-serifless"
five = "upright-arched-serifless"
seven = "straight-serifless-crossbar"
zero = "dotted"
capital-a = "straight-serifless"
capital-g = "toothless-corner-serifless-hooked"
capital-j = "serifless"
capital-q = "crossing"
capital-s = "serifless"
f = "flat-hook-serifless-crossbar-at-x-height"
j = "flat-hook-serifed"
t = "flat-hook-short-neck2"
punctuation-dot = "square"
paren = "flat-arc"
at = "fourfold"
question = "corner"

  [buildPlans.Bersevka.ligations]
  inherits = "clike"

[buildPlans.Bersevka.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Bersevka.weights.Bold]
shape = 700
menu = 700
css = 700
