# https://typeof.net/Iosevka/customizer
[buildPlans.Bersevka]
family = "Bersevka"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.Bersevka.variants.design]
three = "flat-top-serifless"
five = "upright-flat-hook-serifless"
six = "open-contour"
seven = "straight-serifless-crossbar"
eight = "two-circles"
nine = "open-contour"
zero = "dotted"
capital-a = "straight-serifless"
capital-g = "toothless-corner-serifless-hooked"
capital-j = "serifless"
capital-q = "crossing"
capital-s = "serifless"
capital-w = "straight-flat-top-serifless"
f = "flat-hook-serifless-crossbar-at-x-height"
g = "single-storey-serifless"
j = "flat-hook-serifed"
t = "flat-hook-short-neck2"
w = "straight-flat-top-serifless"
tittle = "square"
diacritic-dot = "square"
punctuation-dot = "square"
asterisk = "penta-low"
paren = "normal"
at = "fourfold"
question = "corner"

[buildPlans.Bersevka.variants.italic]
three = "flat-top-serifless"
five = "upright-arched-serifless"
seven = "straight-serifless-crossbar"
zero = "dotted"
capital-a = "straight-serifless"
capital-g = "toothless-corner-serifless-hooked"
capital-j = "serifless"
capital-q = "crossing"
capital-s = "serifless"
a = "double-storey-serifless"
d = "toothed-serifless"
e = "flat-crossbar"
f = "flat-hook-serifless-crossbar-at-x-height"
g = "single-storey-top-cut"
i = "serifed"
j = "flat-hook-serifed"
k = "straight-serifless"
l = "serifed"
t = "flat-hook-short-neck2"
u = "toothed-serifless"
y = "straight-serifless"

  [buildPlans.Bersevka.ligations]
  inherits = "clike"

[buildPlans.Bersevka.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Bersevka.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.Bersevka.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.Bersevka.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.Bersevka.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.Bersevka.widths.SemiExtended]
shape = 548
menu = 6
css = "semi-expanded"

[buildPlans.Bersevka.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.Bersevka.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
